"""Add multi-agent physiotherapy models

Revision ID: 8a2d29e86318
Revises: 4e402d21494b
Create Date: 2025-06-17 15:26:20.959366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2d29e86318'
down_revision: Union[str, None] = '4e402d21494b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('agent_type', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'agent_type')
    op.drop_column('conversations', 'user_id')
    # ### end Alembic commands ###
